---
- name: win restart metricbeat service
  win_service:
    name: metricbeat
    state: restarted
    start_mode: auto

- name: restart metricbeat service
  service:
    name: metricbeat
    state: restarted
